services:
  db:
    image: postgres:15
    container_name: infrawatch-db
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: infrawatch
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: infrawatch-app
    restart: always
    environment:
      TZ: America/Sao_Paulo
      DB_USER: admin
      DB_PASSWORD: password123
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: infrawatch
      PORT: 3000
    depends_on:
      - db
  nginx:
    image: nginx:alpine
    container_name: infrawatch-proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app    

volumes:
  postgres_data: